fail_fast: false
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-ast
    - id: check-json
    - id: check-added-large-files
    - id: detect-private-key # detects the presence of private keys.
    - id: double-quote-string-fixer
    - id: mixed-line-ending
