services:
  ci:
    container_name: cpp_ci_env
    image: cpp_ci_env:latest
    environment:
      - TERM=xterm-256color
    volumes:
      - ${PWD}/../:/home/ci/workspace
    command: sleep infinity
    user: ci
    hostname: cpp_docker_ci_env
