"""Generate one public header from the TypeSafeRegister runtime headers."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


PUBLIC_HEADERS = (
    "AssignmentOperations.h",
    "BitName.h",
    "BitType.h",
    "BitInfo.h",
    "CompileTimeMap.h",
    "details.h",
    "SvdTypes.h",
    "BitField.h",
    "EnumeratedField.h",
    "Output.h",
    "Register.h",
    "RegisterArray.h",
)
LOCAL_INCLUDE = re.compile(r"^#include <([^>]+)>\s*$")


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--include-dir", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    return parser.parse_args()


def remove_local_includes(contents: str) -> str:
    filtered_lines = []
    for line in contents.splitlines(keepends=True):
        include = LOCAL_INCLUDE.match(line.strip())
        if include and include.group(1) in PUBLIC_HEADERS:
            continue
        filtered_lines.append(line)
    return "".join(filtered_lines)


def main() -> None:
    arguments = parse_arguments()
    sections = [
        "// Generated by scripts/amalgamate_headers.py. Do not edit.\n",
        "#pragma once\n",
    ]

    for header_name in PUBLIC_HEADERS:
        header_path = arguments.include_dir / header_name
        if not header_path.is_file():
            raise FileNotFoundError(f"Public header not found: {header_path}")

        contents = header_path.read_text(encoding="utf-8")
        contents = contents.replace("#pragma once\n", "", 1)
        sections.extend(
            (
                f"\n// Begin {header_name}\n",
                remove_local_includes(contents).rstrip(),
                "\n",
            )
        )

    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text("".join(sections), encoding="utf-8")


if __name__ == "__main__":
    main()
